### ISSUE TITLE
Is there a way to remove all styling options?

### ISSUE THREAD

**Issue by nebulousGirl** [DanielFloeter/description-list-block#16]
I love to find a plugin which does only one thing without bloat.

I do not want to have the Styles tab in the Gutenberg editor. Is there a way to remove it?

**Comment by DanielFloeter** [comment]
I can add another Style 'Default' which don't have any settings and only the Theme CSS will be used. 
Can that a solution for you?


To unregister the Block Styles with Javascript put it somewhere to the Gutenberg Backend or try it with the browser developer tools:

```
wp.domReady( () => {
	wp.blocks.unregisterBlockStyle(
		'description-list-block/description-list', [ 'regular', 'grid' ]
	);
} );
```
