### ISSUE TITLE
Remove styling options for custom registered styles

### ISSUE THREAD

**Issue by nebulousGirl** [DanielFloeter/description-list-block#17]
A new issue is probably better for this

=========

I was already unregistering your block styles. I see that the style default does not have the styling options which is cool.

The last thing I would need for this plugin to work for me would be to be able to register my own styles without the plugin's styling options.

Here is the style I'm adding:

```
wp.blocks.registerBlockStyle('description-list-block/description-list', {
		name: '2-columns',
		label: 'Sur 2 colonnes'
	  });
```

Is there a way to disable the styling options for this new style?

_Originally posted by @nebulousGirl in https://github.com/DanielFloeter/description-list-block/issues/16#issuecomment-1012416437_

**Comment by DanielFloeter** [comment]
If you change the name you registerBlockStyle from '2-columns' to 'no-bloat'.
You can give any label you want, like you did with 'Sur 2 colonnes'.

```
wp.blocks.registerBlockStyle('description-list-block/description-list', {
		name: 'no-bloat',
		label: 'Sur 2 colonnes'
	  });
```

If you are interested how to put that Javascript code in WordPress you can check that Add-on for the Gallery core Block: https://github.com/DanielFloeter/gallery-styles
It's a Plugin with a Gutenberg Block you have to install as a normal Plugin to the directory [your-wordpress-installation]/wp-content/plugins and activate it in the WordPress admin page Installed Plugins.

**Comment by nebulousGirl** [comment]
I can't do this. My code would not make sense anymore and I wouldn't be able to add other custom styles if needed. I'm working in an agency that aims to limit what the user can do to ensure the original design is respected.

My technique of registering custom styles is working fine with the native blocks. The one thing I see is different with your plugin is that the "style" is saved as an attribute to the block in your case instead of just in className.

I'm still new to Gutenberg though, so I don't understand it all and I haven't made a block myself yet.

If you don't know of a quick fix, I will try to look into it later myself. I will also look at your other example to try to better understand how to code a block.

**Comment by DanielFloeter** [comment]
It's no problem to support: To remove all settings for registered Custom Block Styles.

The new version is also uploaded to https://wordpress.org/plugins/description-list-block but I haven't made a new version number. 
It's possible to delete the Plugin and re-install it with the WordPress admin Plugins page to get the new code? (Because there is no update link to a new version!)

You can register Block Styles as you mentioned above or with registerBlockType() as styles attribute.

Set-up an blank new Gutenberg Block also to learn from is with the Create Block from here https://developer.wordpress.org/block-editor/getting-started/create-block/

**Comment by nebulousGirl** [comment]
I reinstalled your plugin, but now, I have a JavaScript error when I hover the block in the library:
TypeError: can't access property "current", r is undefined

I'm using Firefox Developer.

**Comment by DanielFloeter** [comment]
I have no error. Also with FF.
You can write to https://tiptoppress.com/contact/ to share screenshots.
I use WP 5.8 and 5.9. For me and all projects it works well

**Comment by DanielFloeter** [comment]
Thanks.
I have to deleted Shortcuts temporally. They also not documented in the core documents: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/ and have issues in the past with other Shortcuts implemented in the core.

@nebulousGirl  Do you need and use the Shortcuts feature?

**Comment by nebulousGirl** [comment]
No I don't need shortcuts.

It's now working as I wanted it to.

A big thank you for your reactivity. I can now use your plugin in my projects.
